function [pdf,ylabel,str] = EMMIXTURE(group,weight,sigma)
group = round(group);
sigma = round(sigma);
weight = round(weight,2);

age = 1:4000;
if length(weight) == 2
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    str = {STR1,STR2};
    
elseif length(weight) == 3
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    str = {STR1,STR2,STR3};

elseif length(weight) == 4
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4));
    pdf = qx(age);
    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    str = {STR1,STR2,STR3,STR4};

elseif length(weight) == 5
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    str = {STR1,STR2,STR3,STR4,STR5};

elseif length(weight) == 6
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6};

elseif length(weight) == 7
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7));
    pdf = qx(age);
    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7};

elseif length(weight) == 8
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8));
    pdf = qx(age);
    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8};

elseif length(weight) == 9
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9));
    pdf = qx(age);
    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9};

elseif length(weight) == 10
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10));
    pdf = qx(age);
    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10};

elseif length(weight) == 11
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11};

elseif length(weight) == 12
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12));
    pdf = qx(age);   

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12};

elseif length(weight) == 13
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13};

elseif length(weight) == 14
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14};

elseif length(weight) == 15
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14))...
        + weight(15) .* normpdf(x,group(15),sigma(15));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14) | age == group(15));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    STR15 = [num2str(group(15)),'¡À',num2str(sigma(15))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14,STR15};

elseif length(weight) == 16
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14))...
        + weight(15) .* normpdf(x,group(15),sigma(15))...
        + weight(16) .* normpdf(x,group(16),sigma(16));
    pdf = qx(age);
    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14) | age == group(15)...
        | age == group(16));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    STR15 = [num2str(group(15)),'¡À',num2str(sigma(15))];
    STR16 = [num2str(group(16)),'¡À',num2str(sigma(16))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14,STR15,STR16};

elseif length(weight) == 17
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14))...
        + weight(15) .* normpdf(x,group(15),sigma(15))...
        + weight(16) .* normpdf(x,group(16),sigma(16))...
        + weight(17) .* normpdf(x,group(17),sigma(17));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14) | age == group(15)...
        | age == group(16) | age == group(17));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    STR15 = [num2str(group(15)),'¡À',num2str(sigma(15))];
    STR16 = [num2str(group(16)),'¡À',num2str(sigma(16))];
    STR17 = [num2str(group(17)),'¡À',num2str(sigma(17))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14,STR15,STR16,STR17};

elseif length(weight) == 18
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14))...
        + weight(15) .* normpdf(x,group(15),sigma(15))...
        + weight(16) .* normpdf(x,group(16),sigma(16))...
        + weight(17) .* normpdf(x,group(17),sigma(17))...
        + weight(18) .* normpdf(x,group(18),sigma(18));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14) | age == group(15)...
        | age == group(16) | age == group(17) | age == group(18));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    STR15 = [num2str(group(15)),'¡À',num2str(sigma(15))];
    STR16 = [num2str(group(16)),'¡À',num2str(sigma(16))];
    STR17 = [num2str(group(17)),'¡À',num2str(sigma(17))];
    STR18 = [num2str(group(18)),'¡À',num2str(sigma(18))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14,STR15,...
        STR16,STR17,STR18};

elseif length(weight) == 19
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14))...
        + weight(15) .* normpdf(x,group(15),sigma(15))...
        + weight(16) .* normpdf(x,group(16),sigma(16))...
        + weight(17) .* normpdf(x,group(17),sigma(17))...
        + weight(18) .* normpdf(x,group(18),sigma(18))...
        + weight(19) .* normpdf(x,group(19),sigma(19));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14) | age == group(15)...
        | age == group(16) | age == group(17) | age == group(18) | age == group(19));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    STR15 = [num2str(group(15)),'¡À',num2str(sigma(15))];
    STR16 = [num2str(group(16)),'¡À',num2str(sigma(16))];
    STR17 = [num2str(group(17)),'¡À',num2str(sigma(17))];
    STR18 = [num2str(group(18)),'¡À',num2str(sigma(18))];
    STR19 = [num2str(group(19)),'¡À',num2str(sigma(19))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14,STR15,...
        STR16,STR17,STR18,STR19};
elseif length(weight) == 20
    qx = @(x) weight(1) .* normpdf(x,group(1),sigma(1))...
        + weight(2) .* normpdf(x,group(2),sigma(2))...
        + weight(3) .* normpdf(x,group(3),sigma(3))...
        + weight(4) .* normpdf(x,group(4),sigma(4))...
        + weight(5) .* normpdf(x,group(5),sigma(5))...
        + weight(6) .* normpdf(x,group(6),sigma(6))...
        + weight(7) .* normpdf(x,group(7),sigma(7))...
        + weight(8) .* normpdf(x,group(8),sigma(8))...
        + weight(9) .* normpdf(x,group(9),sigma(9))...
        + weight(10) .* normpdf(x,group(10),sigma(10))...
        + weight(11) .* normpdf(x,group(11),sigma(11))...
        + weight(12) .* normpdf(x,group(12),sigma(12))...
        + weight(13) .* normpdf(x,group(13),sigma(13))...
        + weight(14) .* normpdf(x,group(14),sigma(14))...
        + weight(15) .* normpdf(x,group(15),sigma(15))...
        + weight(16) .* normpdf(x,group(16),sigma(16))...
        + weight(17) .* normpdf(x,group(17),sigma(17))...
        + weight(18) .* normpdf(x,group(18),sigma(18))...
        + weight(19) .* normpdf(x,group(19),sigma(19))...
        + weight(20) .* normpdf(x,group(20),sigma(20));
    pdf = qx(age);

    index_AGE = find(age == group(1) | age == group(2) | age == group(3)...
        | age == group(4) | age == group(5) | age == group(6) | age == group(7)...
        | age == group(8) | age == group(9) | age == group(10) | age == group(11)...
        | age == group(12) | age == group(13) | age == group(14) | age == group(15)...
        | age == group(16) | age == group(17) | age == group(18) | age == group(19)...
        | age == group(20));
    ylabel = pdf(index_AGE);
    STR1 = [num2str(group(1)),'¡À',num2str(sigma(1))];
    STR2 = [num2str(group(2)),'¡À',num2str(sigma(2))];
    STR3 = [num2str(group(3)),'¡À',num2str(sigma(3))];
    STR4 = [num2str(group(4)),'¡À',num2str(sigma(4))];
    STR5 = [num2str(group(5)),'¡À',num2str(sigma(5))];
    STR6 = [num2str(group(6)),'¡À',num2str(sigma(6))];
    STR7 = [num2str(group(7)),'¡À',num2str(sigma(7))];
    STR8 = [num2str(group(8)),'¡À',num2str(sigma(8))];
    STR9 = [num2str(group(9)),'¡À',num2str(sigma(9))];
    STR10 = [num2str(group(10)),'¡À',num2str(sigma(10))];
    STR11 = [num2str(group(11)),'¡À',num2str(sigma(11))];
    STR12 = [num2str(group(12)),'¡À',num2str(sigma(12))];
    STR13 = [num2str(group(13)),'¡À',num2str(sigma(13))];
    STR14 = [num2str(group(14)),'¡À',num2str(sigma(14))];
    STR15 = [num2str(group(15)),'¡À',num2str(sigma(15))];
    STR16 = [num2str(group(16)),'¡À',num2str(sigma(16))];
    STR17 = [num2str(group(17)),'¡À',num2str(sigma(17))];
    STR18 = [num2str(group(18)),'¡À',num2str(sigma(18))];    
    STR19 = [num2str(group(19)),'¡À',num2str(sigma(19))];
    STR20 = [num2str(group(20)),'¡À',num2str(sigma(20))];
    str = {STR1,STR2,STR3,STR4,STR5,STR6,STR7,STR8,STR9,STR10,STR11,STR12,STR13,STR14,STR15,...
        STR16,STR17,STR18,STR19,STR20};
end
end